data:extend(
{
  	{
		type = "item",
		name = "tile-miner",
		icon = "__bucketwheels-withvisual__/graphics/icons/bucketW-mkI.png",
        icon_size = 32,
		flags = {},
		subgroup="tile-miner",
		place_result = "tile-miner",
		stack_size = 128
	},{
		type = "item",
		name = "tile-miner-b",
		icon = "__bucketwheels-withvisual__/graphics/icons/bucketW-mkI.png",
        icon_size = 32,
		flags = {},
		subgroup="tile-miner-b",
		place_result = "tile-miner-b",
		stack_size = 128
	},{
		type = "item",
		name = "tile-miner-l",
		icon = "__bucketwheels-withvisual__/graphics/icons/bucketW-mkI.png",
        icon_size = 32,
		flags = {},
		subgroup="tile-miner-b",
		place_result = "tile-miner-l",
		stack_size = 128
	},{
		type = "item",
		name = "tile-miner-3",
		icon = "__bucketwheels-withvisual__/graphics/icons/bucketW-mkIII.png",
        icon_size = 32,
		flags = {},
		subgroup="tile-miner-b",
		place_result = "tile-miner-3",
		stack_size = 128
	},{
		type = "item",
		name = "tile-miner-op",
		icon = "__bucketwheels-withvisual__/graphics/icons/bucketW-mkI.png",
        icon_size = 32,
		flags = {},
		subgroup="tile-miner",
		place_result = "tile-miner-op",
		stack_size = 128
	},{
		type = "item",
		name = "tile-miner-e3",
		icon = "__bucketwheels-withvisual__/graphics/icons/bucketW-mkIII.png",
        icon_size = 32,
		flags = {},
		subgroup="tile-miner",
		place_result = "tile-miner-e3",
		stack_size = 128
	}
})
