data:extend({{
		type = "item-group",
		name = "tile-miner",
        icon = "__bucketwheels-withvisual__/graphics/icons/bucketW-mkI.png",
		icon_size = 32
	},{
		type = "item-subgroup",
		name = "tile-miner",group="tile-miner",
        icon = "__bucketwheels-withvisual__/graphics/icons/bucketW-mkI.png",
		icon_size = 32
	},{
		type = "item-subgroup",
		name = "tile-miner-b",group="tile-miner",
        icon = "__bucketwheels-withvisual__/graphics/icons/bucketW-mkI.png",
		icon_size = 32
	}})
require("prototypes.entities")
require("prototypes.items")
require("prototypes.recipes")
require("prototypes.tech")